@echo off

mode 78,24
title TROJAN WIN.32 BY MR-T-N-D

color a
echo.
echo TROJAN WIN.32 BY MR-T-N-D
echo.
set /p x-Server-Target:                            Masukin Yang Bener
echo.
search Ping %x%
ping %x% 
@ping.exe %x% -n 7 -w 2134> nul
goto Next
:Next
echo.
echo.
echo.
set /p m=ip Yang Mau Lo Attack Todd:v:
echo.
set /p n=Packet Size:
echo.
echo.
:TROJAN WIN.32
echo Attacking Server With TROJAN WIN.32 TO %m%
ping %n% -i %n% -t >nul
goto TROJAN WIN.32